# Generated by Django 5.0.2 on 2024-02-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_note_createdon_note_unique_etudiant_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
