# Generated by Django 5.0.2 on 2024-02-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_note_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
